FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGVudnZhci1vcGVyYXRvcgpkZXNjcmlwdGlvbjogIlRoZSBPcGVy\
YXRvciBpbml0aWFsaXNlcyBjb250YWluZXIgRW52aXJvbm1lbnQgVmFyaWFibGVzIGZyb20gQ29u\
ZmlnTWFwcyIKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAptZXRhZGF0YToKICBkaXNw\
bGF5TmFtZTogRW52aXJvbm1lbnQgVmFyaWFibGUgT3BlcmF0b3IKIyAgbG9uZ0Rlc2NyaXB0aW9u\
OgogIGltYWdlVXJsOiAiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL3Nqd29vZG1h\
bi9lbnYtdmFyLWFwYi9vcGVyYXRvci9pY29uLnN2Zz9zYW5pdGl6ZT10cnVlIgogIHByb3ZpZGVy\
RGlzcGxheU5hbWU6ICJSZWQgSGF0LCBJbmMuIgpwbGFuczoKICAtIG5hbWU6IGRlZmF1bHQKICAg\
IGRlc2NyaXB0aW9uOiBUaGlzIHBsYW4gZGVwbG95cyB0aGUgRW52aXJvbWVudCBWYXJpYWJsZSBv\
cGVyYXRvcgogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAgICBwYXJhbWV0ZXJzOiBb\
XQo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
