FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGV2ZW50LWdhdGV3YXkKZGVzY3JpcHRpb246IEVudmlyb25tZW50\
IFZhcmlhYmxlIE9wZXJhdG9yCmJpbmRhYmxlOiBGYWxzZQphc3luYzogb3B0aW9uYWwKbWV0YWRh\
dGE6CiAgZGlzcGxheU5hbWU6IEVudmlyb25tZW50IFZhcmlhYmxlIE9wZXJhdG9yCiAgbG9uZ0Rl\
c2NyaXB0aW9uOiAiS2VlcCB0aGUgcGF5bG9hZCBvZiBDb25maWcgTWFwcyBzeW5jcm9uaXNlZCB3\
aXRoIGNvbnRhaW5lciBFbnZpcm9ubW5ldCBWYXJpYWJsZXMiCiAgaW1hZ2VVcmw6ICJodHRwczov\
L2F2YXRhcnMyLmdpdGh1YnVzZXJjb250ZW50LmNvbS91LzMyMDc2ODI4P3M9MjAwJnY9NCIKICBw\
cm92aWRlckRpc3BsYXlOYW1lOiAiUmVkIEhhdCwgSW5jLiIKcGxhbnM6CiAgLSBuYW1lOiBkZWZh\
dWx0CiAgICBkZXNjcmlwdGlvbjogVGhpcyBkZWZhdWx0IHBsYW4gZGVwbG95cyB0aGUgZW52aXJv\
bWVudCB2YXJpYWJsZSBvcGVyYXRvcgogICAgZnJlZTogVHJ1ZQogICAgbWV0YWRhdGE6IHt9CiAg\
ICBwYXJhbWV0ZXJzOiBbXQo="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
