FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGVudnZhci1vcGVyYXRvcgpkZXNjcmlwdGlvbjogIlRoZSBPcGVy\
YXRvciBpbml0aWFsaXNlcyBjb250YWluZXIgRW52aXJvbm1lbnQgVmFyaWFibGVzIGZyb20gQ29u\
ZmlnTWFwcyIKYmluZGFibGU6IEZhbHNlCmFzeW5jOiBvcHRpb25hbAptZXRhZGF0YToKICBkaXNw\
bGF5TmFtZTogRW52aXJvbm1lbnQgVmFyaWFibGUgT3BlcmF0b3IKICBpbWFnZVVybDogImh0dHBz\
Oi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9zandvb2RtYW4vZW52LXZhci1hcGIvb3BlcmF0\
b3IvaWNvbi5zdmc/c2FuaXRpemU9dHJ1ZSIKICBwcm92aWRlckRpc3BsYXlOYW1lOiAiUmVkIEhh\
dCwgSW5jLiIKcGxhbnM6CiAgLSBuYW1lOiBkZWZhdWx0CiAgICBkZXNjcmlwdGlvbjogVGhpcyBw\
bGFuIGRlcGxveXMgdGhlIEVudmlyb21lbnQgVmFyaWFibGUgb3BlcmF0b3IKICAgIGZyZWU6IFRy\
dWUKICAgIG1ldGFkYXRhOiB7fQogICAgcGFyYW1ldGVyczogW10K"

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
